DROP TABLE IF EXISTS public.user_group;
CREATE TABLE public.user_group
(
    id   int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(32) NOT NULL,
    primary key (id)
);

DROP TABLE IF EXISTS public.user;
CREATE TABLE public.user
(
    id          int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account     varchar(32) NOT NULL,
    create_time timestamp   NOT NULL,
    email       varchar(64) NOT NULL,
    first_name  varchar(32) NOT NULL,
    last_name   varchar(32) NOT NULL,
    "password"  varchar(32) NOT NULL,
    username    varchar(32) NULL,
    PRIMARY KEY (id)
);