DROP TABLE IF EXISTS public.community_user_group;
CREATE TABLE public.community_user_group
(
    id   int8        NOT NULL,
    name varchar(32) NOT NULL,
    primary key (id)
);

DROP TABLE IF EXISTS public.community_user;
CREATE TABLE public.community_user
(
    id          int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_id    int8        NOT NULL,
    user_status int2        NOT NULL,
    account     varchar(32) NOT NULL,
    create_time timestamp   NOT NULL,
    email       varchar(64) NOT NULL,
    first_name  varchar(32) NOT NULL,
    last_name   varchar(32) NOT NULL,
    "password"  varchar(32) NOT NULL,
    username    varchar(32) NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.community_post;
CREATE TABLE public.community_post
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     int8         NOT NULL,
    subject     varchar(128) NOT NULL,
    content     text         NOT NULL,
    create_time timestamp    NOT NULL,
    update_time timestamp    NOT NULL,
    PRIMARY KEY (id)
)

